server:
  port: 8001
spring:
  data:
    mongodb:
      database: "casita"
      uri: ${MONGO_DB_URI}
okta:
  oauth2:
    issuer: "https://${OKTA_ISSUER_DOMAIN}/"
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}